languages:
- typescript
- bash
- markdown

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths:
- dist/
- "**/node_modules/**"
- "**/.bun/**"
- "**/.serena/**"

read_only: false

excluded_tools: []

project_name: "orca-env-plugin"

included_optional_tools: []

base_modes:

default_modes:

fixed_tools: []

symbol_info_budget:

language_backend:

line_ending:

read_only_memory_patterns: []

ignored_memory_patterns: []

ls_specific_settings: {}
